### PR TITLE
Add a lot of new functionalities when using pebble with Spring

### PR DESCRIPTION
**Pull request by ebussieres**
I'm currently using Pebble with Spring and I feel like it lacks a lot of basic functionalities. So I have decided to add them. Here it comes :

## Access to Spring beans

Spring beans are now available to the template. Syntax is like this :

```javascript
{{ beans.beanname }}
```
## Access to http request

HttpRequest is available like this. Really useful to get the context path when outputting href

```javascript
{{ request.contextPath }}
```

## Access to http session

HttpSession is available like this.

```javascript
{{ session.maxInactiveInterval }}
```

## New Spring extension

I created a new extension (SpringExtension). Currently, it has many functions for spring validation and the use of message bundle.

Because of the new pebble engine builder, it can't no more be automatically created.
Here's an example of configuration

```java
@Configuration
@EnableWebMvc
public class MvcConfig extends WebMvcConfigurerAdapter {
    
    @Autowired
    private ServletContext servletContext;
    
    @Bean
    public Loader templateLoader(){
        return new ServletLoader(servletContext);
    }

    @Bean
    public SpringExtension springExtension() {
        return new SpringExtension();
    }

    @Bean 
    public PebbleEngine pebbleEngine() {
         return new PebbleEngine.Builder()
                .loader(this.templateLoader())
                .strictVariables(false)
                .extension(springExtension())
                .build();
    }

    @Bean
    public ViewResolver viewResolver() {
        PebbleViewResolver viewResolver = new PebbleViewResolver();
        viewResolver.setPrefix("/WEB-INF/templates/");
        viewResolver.setSuffix(".html");
        viewResolver.setPebbleEngine(pebbleEngine());
        return viewResolver;
    }
}
```

#### Message function
It achieves the same thing as the i18n function, but instead, it uses the configured spring messageSource, typically the ResourceBundleMessageSource.

```javascript
Label = {{ message('label.test') }}
Label with params = {{ message('label.test.params', 'params1', 'params2') }}
```

#### Spring validations and error messages
I have exposed 6 methods for validations and error messages (BindingResult). We need to pass as a string the form name and for a particular field, the field name.

To check if there's any error:
```javascript
{{ hasErrors('formName' }}

{{ hasGlobalErrors('formName' }}

{{ hasFieldErrors('formName', 'fieldName' }}
```

To output any error:
```javascript
{% for err in getAllErrors('formName') %}
    <p>{{ err }}</p>
{% endfor %}

{% for err in getGlobalErrors('formName') %}
    <p>{{ err }}</p>
{% endfor %}

{% for err in getFieldErrors('formName', 'fieldName') %}
    <p>{{ err }}</p>
{% endfor %}
```

## Timer

I also have added a timer in PebbleView that outputs the time taken to process a template. Just add the following config to your log4j.xml

```xml
<Logger name="com.mitchellbosecke.pebble.spring.PebbleView.timer" level="DEBUG" additivity="false">
      <AppenderRef ref="STDOUT" />
</Logger> 
```

## Unit test

I have also added a unit test for all this since there was none.

### CODE REVIEW

**Comment by mbosecke** [comment]
You were right, this library was definitely missing a lot of basic functionality and it really needed some loving. This all looks really great, thanks for the effort you've put into this. Bear with me though while I spend some time looking/understanding all the changes before I merge it all in.

**Comment by ebussieres** [comment]
I'll be glad to help you understanding if you have any questions

**Comment by ebussieres** [comment]
There's no pebble snapshot available, so the build is broken. But it works flawlessly on my workstation

**Comment by ebussieres** [comment]
@mbosecke Did you have time to look into this PR ?

**Comment by hectorlf** [comment]
I'm interested in this one too, because I was going to do the exact same thing!

**Comment by mbosecke** [comment]
Sorry for taking so unbelievably long to merge this one in. This is such a massive improvement to the pebble-spring3 library so thanks a lot.

**Comment by hectorlf** [comment]
I'd like to raise a question for debate, though!

The SpringExtension conceptually fits into this project, but I have a small doubt about how convenient it is to have them fused. I have 2 projects that I'd like to contribute (I'll open an issue to discuss this tomorrow), one being a SpringSecurityExtension. Wouldn't it be clearer to have them separated into its own projects?

**Pull request merged**
